[projects]

  [projects.default]
  contents = [
    "preface",
    "start",
    "git",
    "editing",
    "pandoc",
    "julia",
    "data",
    "statistics",
    "frequentist",
    "ci",
    "appendix",
    "references"
  ]
  port = 8004
  output_filename = "tools"
