module Tools

export build

const project_root = dirname(dirname(pathof(Tools)))
const target_dir = joinpath(project_root, "build", "files")

function git_version_text()
    io = IOBuffer()
    cmd = `git rev-parse HEAD`
    run(pipeline(cmd; stdout=io))
    out = String(take!(io))
    hash = strip(out)
    text = """
    This document is generated by <https://github.com/rikhuijzer/tools> at commit `$hash`.
    """
    path = joinpath(target_dir, "git-commit.md")
    write(path, text)
    text
end

function build()
    mkpath(target_dir)
    git_version_text()

end

end # module
