module Tools

import Books
import Pkg

const project_root = dirname(dirname(pathof(Tools)))
const build_dir = joinpath(project_root, "build")

function git_version_text()
    io = IOBuffer()
    cmd = `git rev-parse HEAD`
    run(pipeline(cmd; stdout=io))
    out = String(take!(io))
    hash = strip(out)
    text = """
    Specifically, it is generated by <https://github.com/rikhuijzer/tools> at commit `$hash`.
    """
end

function versions()
    io = IOBuffer()
    Pkg.status(; io)
    text = String(take!(io))
    lines = split(text, '\n')[3:end-1]
    lines_without_id = [l[14:end] for l in lines]
    pkgs = join(lines_without_id, '\n')

    text = """
    This website is built with Julia $VERSION and
    
    ```
    $pkgs
    ```
    """
end

function all_version_text()
    text = """
    $(versions())
    
    $(git_version_text())
    """
    path = joinpath(build_dir, "versions.md")
    write(path, text)
end

function build_all()
    println("Building tools")
    rm(build_dir; force=true, recursive=true)
    mkpath(build_dir)
    all_version_text()
    Books.build_all()
end

end # module
